// C driver for Arm64 code generated by Arm64.fs and Arm64Comp.fs and
// by clang's assembler, for Linux, MacOS and Windows on Arm (WOA).
// Defines the initial entrypoint (main) which calls the assembly
// entrypoint (asm_main), and defines utility functions (printc,
// printf, checkargc) called from the assembly code.

// In MacOS assembly code files, but not in this C code file nor in
// Linux or Windows assembly code, global names must be prefixed by an
// underscore: _asm_main, _printc, _printi and _checkargc.

// The <stdint.h>, int64_t and intmax_t stuff is needed because clang
// type long is 64 bits on Linux and MacOS but 32 bits on Windows, so
// we need the portable int64_t.  Then printf adds more complications.

// sestoft@itu.dk * 2026-07-27 based on Kokholm's 2002 x86 version 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <time.h>

extern void asm_main(int64_t, int64_t*);

int64_t printc(int64_t c) { printf("%c", (int)c); return c; }

int64_t printi(int64_t i) { printf("%jd ", (intmax_t)i); return i; }

void checkargc(int64_t given, int64_t expected) { 
  if (given > 8) {
    printf("More than 8 command line arguments: %jd\n", (intmax_t)given); 
    exit(1);
  }
  if (given != expected) {
    printf("Wrong argument count: expected %jd but got %jd\n", (intmax_t)expected, (intmax_t)given); 
    exit(1);
  }
}

int main(int argc, char **argv) {
  int64_t args[63];
  for (int i=1; i<argc; i++) 
    args[i-1] = atol(argv[i]);
  asm_main(argc-1,args);
  printf("\nRan %.3f s\n", (clock())*1.0/CLOCKS_PER_SEC);
  exit(0);
}
